### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Alberto100591** [AdaptiveMotorControlLab/Camera_Control#3]
Hello my name is Alberto, today i would like to request help with the followed problem, but first i will describe it

My Operating system and DeepLabCut version*
Windows 10, with an Anaconda Env, & deeplabcut 2.1.8.2

Please complete the following information about your system:

OS: [Windows 10]
Deeplabcut 2.1.8.2
Anaconda env used:

Describe the problem

In this moment i am working with 3D DeepLabCut, so i followed the instructions (https://github.com/DeepLabCut/DeepLabCut/blob/a3ff917fc04ae0199b051b1d0cc2f75c3700191a/docs/Overviewof3D.md ) ,everything was going fine until, i tried to install Camera Control; i followed the instructions (https://github.com/AdaptiveMotorControlLab/Camera_Control) , i know the process installation is very simple , but for some strange reason my computer showed this:

**_Important Note: The picture appears when i run as administrator "install 1"_**

![FinalImage_1](https://user-images.githubusercontent.com/68699532/93945559-c842ca80-fcfc-11ea-9e74-713bcdde7eef.jpg)

Please ,could you help me with my problem?

**Comment by MMathisLab** [comment]
do you have FFMPEG installed?

**Comment by Alberto100591** [comment]
yes i have, but for some reason i cannot install camera_control.


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Mackenzie Mathis <notifications@github.com>
Enviado: jueves, 24 de septiembre de 2020 09:54 p. m.
Para: AdaptiveMotorControlLab/Camera_Control <Camera_Control@noreply.github.com>
CC: Alberto100591 <descargas117@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [AdaptiveMotorControlLab/Camera_Control] Problem with installation (#3)


do you have FFMPEG installed?

**Comment by Alberto100591** [comment]
Hello my name is Alberto Lopez , currently i am working with DeepLabCut 3D, but i have had few problem with the installation of Camera Control , so i will describe the problem:
Problem Description:
My problem is that i cannot install Camera Control because ffmpeg library can not download because de link of the page is broken 
Image 1.- damaged link 
![1](https://user-images.githubusercontent.com/68699532/94866897-c7e5b600-0405-11eb-93ef-27f29cdf3042.png)
Image 2.- damaged link (the page closed 18/Sep/2020)

![2](https://user-images.githubusercontent.com/68699532/94866905-cb793d00-0405-11eb-8da9-c5fe530fc28d.png)
Could you help me?

**Comment by MMathisLab** [comment]
http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/

**Comment by Alberto100591** [comment]
> 
> 
> http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/

Good afternoon, I'm sorry to bother again, I already checked the information you sent me, the problem is that the zeranoe page stopped working on Sep 18, 2020 and I cannot download the files for ffmpeg, could you help me with this situation? Is there any other how to install control camera?
Do you have any other recording software that you recommend?

**Comment by benefron** [comment]
Hi I am having the same problem.
Do you have an updated link for?
Ben

**Comment by MMathisLab** [comment]
https://anaconda.org/conda-forge/ffmpeg

**Comment by benefron** [comment]
What do I need to change in the .bat file for this to work?

**Comment by MMathisLab** [comment]
If you look at the frist bat, it installs ffmpeg then creates a conda env. You can simply add ffmpeg to the conda yaml file, and remove the installation within the bat.

**Comment by DuanWei-fudan** [comment]
I removed the ffmpeg within the bat and added it in the conda yaml file.
But when I iniatilze camrea, no resopnse for that . And the command window gives the message below:
_Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\Anaconda\envs\camera27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "camera_control_GUI.py", line 379, in <lambda>
    Button(self.window, text="Initialize Camera 1", command=lambda:self.init_cam(0)).grid(sticky="nsew", row=cur_row+1, column=0, columnspan=2)
  File "camera_control_GUI.py", line 77, in init_cam
    self.cam.append(ICCam(cam_num))
  File "C:\Users\admin\camera_control\ic_camera.py", line 42, in __init__
    self.cam = self.ic_ic.get_device(self.ic_ic.get_unique_device_names()[self.cam_num])
IndexError: list index out of range_

So it means my camera can't be recognized?
