### ISSUE TITLE
Intel Realsense Camera

### ISSUE THREAD

**Issue by Wulin-Tan** [AdaptiveMotorControlLab/Camera_Control#4]
Hi, I am new in this field. And I have some intel realsense cameras instead of the imaging source cameras you recommended. 
How can I modify this program to adapt to reasense cameras?
thank you

**Comment by MMathisLab** [comment]
Hi @Wulin-Tan welcome - right now we only support Imaging Source with this GUI, but our other GUI supports more options: https://github.com/DeepLabCut/DeepLabCut-live-GUI
